telegram_user_account: telegram_bot
telegram_checkout_location: /home/{{ telegram_user_account }}/telegram-bot
telegram_bot_virtual_env_location: /home/{{ telegram_user_account }}/telegram-virtual-env
telegram_bot_repo: https://github.com/avinash-oza/telegram-bot.git
telegram_user_public_key_location: /tmp/telegram-bot-ssh.pub
telegram_log_location: /var/log/custom-logs/telegram-bot
telegram_alerts_endpoint: http://localhost:25001/send_nagios_alert
