# runs only when raid_mount_ip_address is defined
- name: Install required packages CENTOS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-utils
  when: ansible_distribution == "CentOS" # freepbx is centos

- name: Install required packages Debian
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-common
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"  # freepbx is centos

- name: "Make mount point /mnt/raid0"
  become: true
  file:
    path: "/mnt/raid0"
    state: directory

- name: "Create raid mount in fstab"
  become: true
  mount:
    name: /mnt/raid0
    src: "{{ raid_mount_ip_address }}:/mnt/raid0"
    fstype: nfs
    opts: nolock
    state: mounted
