---
- import_tasks: configure-deploy-user-for-sudo.yaml
- import_tasks: base-configuration.yaml
- import_tasks: configure-environment-for-user.yaml
- import_tasks: secure-server.yaml
- import_tasks: scramble-extra-users-passwords.yaml

- name: Create raid mount in fstab
  import_tasks: add-raid-mount.yaml
  when: raid_mount_ip_address is defined
